package kotlin.reflect.jvm.internal.impl.load.java.typeEnhancement;

import java.util.Map;
import kotlin.reflect.jvm.internal.impl.load.java.typeEnhancement.SignatureEnhancementBuilder.ClassEnhancementBuilder;
import kotlin.reflect.jvm.internal.impl.load.kotlin.SignatureBuildingComponents;

/* compiled from: predefinedEnhancementInfo.kt */
public final class PredefinedEnhancementInfoKt {
    /* access modifiers changed from: private */
    public static final JavaTypeQualifiers NOT_NULLABLE;
    /* access modifiers changed from: private */
    public static final JavaTypeQualifiers NOT_PLATFORM;
    /* access modifiers changed from: private */
    public static final JavaTypeQualifiers NULLABLE;
    private static final Map<String, PredefinedFunctionEnhancementInfo> PREDEFINED_FUNCTION_ENHANCEMENT_INFO_BY_SIGNATURE;

    static {
        JavaTypeQualifiers javaTypeQualifiers = new JavaTypeQualifiers(NullabilityQualifier.NULLABLE, null, false, false, 8, null);
        NULLABLE = javaTypeQualifiers;
        JavaTypeQualifiers javaTypeQualifiers2 = new JavaTypeQualifiers(NullabilityQualifier.NOT_NULL, null, false, false, 8, null);
        NOT_PLATFORM = javaTypeQualifiers2;
        JavaTypeQualifiers javaTypeQualifiers3 = new JavaTypeQualifiers(NullabilityQualifier.NOT_NULL, null, true, false, 8, null);
        NOT_NULLABLE = javaTypeQualifiers3;
        SignatureBuildingComponents signatureBuildingComponents = SignatureBuildingComponents.INSTANCE;
        String javaLang = signatureBuildingComponents.javaLang("Object");
        String javaFunction = signatureBuildingComponents.javaFunction("Predicate");
        String javaFunction2 = signatureBuildingComponents.javaFunction("Function");
        String javaFunction3 = signatureBuildingComponents.javaFunction("Consumer");
        String javaFunction4 = signatureBuildingComponents.javaFunction("BiFunction");
        String javaFunction5 = signatureBuildingComponents.javaFunction("BiConsumer");
        String javaFunction6 = signatureBuildingComponents.javaFunction("UnaryOperator");
        String javaUtil = signatureBuildingComponents.javaUtil("stream/Stream");
        String javaUtil2 = signatureBuildingComponents.javaUtil("Optional");
        SignatureEnhancementBuilder signatureEnhancementBuilder = new SignatureEnhancementBuilder();
        SignatureBuildingComponents signatureBuildingComponents2 = signatureBuildingComponents;
        String str = javaFunction3;
        String str2 = javaFunction;
        String str3 = javaFunction;
        C12980xd5dbd441 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$1 = r8;
        String str4 = javaUtil;
        String str5 = javaFunction3;
        ClassEnhancementBuilder classEnhancementBuilder = new ClassEnhancementBuilder(signatureBuildingComponents.javaUtil("Iterator"));
        String str6 = javaFunction6;
        String str7 = javaFunction6;
        SignatureEnhancementBuilder signatureEnhancementBuilder2 = signatureEnhancementBuilder;
        String str8 = javaFunction5;
        String str9 = javaUtil2;
        String str10 = javaLang;
        String str11 = javaFunction4;
        String str12 = javaFunction2;
        String str13 = str9;
        C12980xd5dbd441 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$12 = new C12980xd5dbd441(signatureBuildingComponents2, str, str2, str4, str6, str8, str10, str11, str12, str13);
        classEnhancementBuilder.function("forEachRemaining", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$1);
        ClassEnhancementBuilder classEnhancementBuilder2 = new ClassEnhancementBuilder(signatureBuildingComponents.javaLang("Iterable"));
        String str14 = str5;
        String str15 = str3;
        String str16 = str7;
        C12991xd5dbd442 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$2 = new C12991xd5dbd442(signatureBuildingComponents2, str14, str15, str4, str16, str8, str10, str11, str12, str13);
        classEnhancementBuilder2.function("spliterator", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$2);
        ClassEnhancementBuilder classEnhancementBuilder3 = new ClassEnhancementBuilder(signatureBuildingComponents.javaUtil("Collection"));
        C13001xd5dbd443 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$3 = new C13001xd5dbd443(signatureBuildingComponents2, str14, str15, str4, str16, str8, str10, str11, str12, str13);
        classEnhancementBuilder3.function("removeIf", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$3);
        C13002xd5dbd444 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$4 = new C13002xd5dbd444(signatureBuildingComponents2, str14, str15, str4, str16, str8, str10, str11, str12, str13);
        classEnhancementBuilder3.function("stream", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$4);
        C13003xd5dbd445 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$5 = new C13003xd5dbd445(signatureBuildingComponents2, str14, str15, str4, str16, str8, str10, str11, str12, str13);
        classEnhancementBuilder3.function("parallelStream", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$5);
        ClassEnhancementBuilder classEnhancementBuilder4 = new ClassEnhancementBuilder(signatureBuildingComponents.javaUtil("List"));
        C13004xd5dbd446 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$6 = new C13004xd5dbd446(signatureBuildingComponents2, str14, str15, str4, str16, str8, str10, str11, str12, str13);
        String str17 = "replaceAll";
        classEnhancementBuilder4.function(str17, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$6);
        ClassEnhancementBuilder classEnhancementBuilder5 = new ClassEnhancementBuilder(signatureBuildingComponents.javaUtil("Map"));
        SignatureEnhancementBuilder signatureEnhancementBuilder3 = signatureEnhancementBuilder2;
        String str18 = str17;
        String str19 = javaLang;
        C13005xd5dbd447 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$7 = new C13005xd5dbd447(signatureBuildingComponents2, str14, str15, str4, str16, str8, str19, str11, str12, str13);
        classEnhancementBuilder5.function("forEach", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$7);
        C13006xd5dbd448 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$8 = new C13006xd5dbd448(signatureBuildingComponents2, str14, str15, str4, str16, str8, str19, str11, str12, str13);
        classEnhancementBuilder5.function("putIfAbsent", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$8);
        C13007xd5dbd449 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$9 = new C13007xd5dbd449(signatureBuildingComponents2, str14, str15, str4, str16, str8, str19, str11, str12, str13);
        String str20 = "replace";
        classEnhancementBuilder5.function(str20, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$9);
        String str21 = str18;
        String str22 = str20;
        String str23 = javaLang;
        C12981xe59eb40f predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$10 = new C12981xe59eb40f(signatureBuildingComponents2, str14, str15, str4, str16, str8, str23, str11, str12, str13);
        classEnhancementBuilder5.function(str22, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$10);
        C12982xe59eb410 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$11 = new C12982xe59eb410(signatureBuildingComponents2, str14, str15, str4, str16, str8, str23, str11, str12, str13);
        classEnhancementBuilder5.function(str21, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$11);
        C12983xe59eb411 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$122 = new C12983xe59eb411(signatureBuildingComponents2, str14, str15, str4, str16, str8, str23, str11, str12, str13);
        classEnhancementBuilder5.function("compute", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$122);
        C12984xe59eb412 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$13 = new C12984xe59eb412(signatureBuildingComponents2, str14, str15, str4, str16, str8, str23, str11, str12, str13);
        classEnhancementBuilder5.function("computeIfAbsent", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$13);
        C12985xe59eb413 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$14 = new C12985xe59eb413(signatureBuildingComponents2, str14, str15, str4, str16, str8, str23, str11, str12, str13);
        classEnhancementBuilder5.function("computeIfPresent", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$14);
        C12986xe59eb414 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$15 = new C12986xe59eb414(signatureBuildingComponents2, str14, str15, str4, str16, str8, str23, str11, str12, str13);
        classEnhancementBuilder5.function("merge", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$15);
        String str24 = str9;
        ClassEnhancementBuilder classEnhancementBuilder6 = new ClassEnhancementBuilder(str24);
        C12987xe59eb415 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$16 = r8;
        String str25 = javaLang;
        String str26 = str24;
        C12987xe59eb415 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$162 = new C12987xe59eb415(signatureBuildingComponents2, str14, str15, str4, str16, str8, str25, str11, str12, str26);
        classEnhancementBuilder6.function("empty", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$16);
        C12988xe59eb416 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$17 = new C12988xe59eb416(signatureBuildingComponents2, str14, str15, str4, str16, str8, str25, str11, str12, str26);
        classEnhancementBuilder6.function("of", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$17);
        C12989xe59eb417 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$18 = new C12989xe59eb417(signatureBuildingComponents2, str14, str15, str4, str16, str8, str25, str11, str12, str26);
        classEnhancementBuilder6.function("ofNullable", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$18);
        C12990xe59eb418 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$19 = new C12990xe59eb418(signatureBuildingComponents2, str14, str15, str4, str16, str8, str25, str11, str12, str26);
        String str27 = "get";
        classEnhancementBuilder6.function(str27, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$19);
        String str28 = str27;
        C12992xe59eb42e predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$20 = new C12992xe59eb42e(signatureBuildingComponents2, str14, str15, str4, str16, str8, javaLang, str11, str12, str26);
        classEnhancementBuilder6.function("ifPresent", predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$20);
        SignatureEnhancementBuilder signatureEnhancementBuilder4 = signatureEnhancementBuilder3;
        ClassEnhancementBuilder classEnhancementBuilder7 = new ClassEnhancementBuilder(signatureBuildingComponents.javaLang("ref/Reference"));
        String str29 = javaFunction5;
        SignatureEnhancementBuilder signatureEnhancementBuilder5 = signatureEnhancementBuilder4;
        C12993xe59eb42f predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$21 = new C12993xe59eb42f(signatureBuildingComponents2, str14, str15, str4, str16, str8, javaLang, str11, str12, str26);
        String str30 = str28;
        classEnhancementBuilder7.function(str30, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$21);
        String str31 = str3;
        ClassEnhancementBuilder classEnhancementBuilder8 = new ClassEnhancementBuilder(str31);
        String str32 = str31;
        C12994xe59eb430 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$22 = r8;
        String str33 = str29;
        String str34 = str30;
        C12994xe59eb430 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$222 = new C12994xe59eb430(signatureBuildingComponents2, str14, str32, str4, str16, str33, javaLang, str11, str12, str26);
        String str35 = "test";
        classEnhancementBuilder8.function(str35, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$22);
        ClassEnhancementBuilder classEnhancementBuilder9 = new ClassEnhancementBuilder(signatureBuildingComponents.javaFunction("BiPredicate"));
        String str36 = str3;
        SignatureBuildingComponents signatureBuildingComponents3 = signatureBuildingComponents;
        String str37 = str35;
        String str38 = javaLang;
        C12995xe59eb431 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$23 = new C12995xe59eb431(signatureBuildingComponents2, str14, str36, str4, str16, str33, str38, str11, str12, str26);
        classEnhancementBuilder9.function(str37, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$23);
        String str39 = str5;
        ClassEnhancementBuilder classEnhancementBuilder10 = new ClassEnhancementBuilder(str39);
        SignatureBuildingComponents signatureBuildingComponents4 = signatureBuildingComponents3;
        String str40 = str39;
        C12996xe59eb432 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$24 = new C12996xe59eb432(signatureBuildingComponents4, str40, str36, str4, str16, str33, str38, str11, str12, str26);
        String str41 = "accept";
        classEnhancementBuilder10.function(str41, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$24);
        String str42 = str29;
        ClassEnhancementBuilder classEnhancementBuilder11 = new ClassEnhancementBuilder(str42);
        C12997xe59eb433 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$25 = r8;
        String str43 = str42;
        String str44 = str41;
        String str45 = javaLang;
        C12997xe59eb433 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$252 = new C12997xe59eb433(signatureBuildingComponents4, str40, str36, str4, str16, str43, str45, str11, str12, str26);
        classEnhancementBuilder11.function(str44, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$25);
        ClassEnhancementBuilder classEnhancementBuilder12 = new ClassEnhancementBuilder(javaFunction2);
        String str46 = str5;
        String str47 = str29;
        C12998xe59eb434 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$26 = new C12998xe59eb434(signatureBuildingComponents4, str46, str36, str4, str16, str47, str45, str11, str12, str26);
        String str48 = "apply";
        classEnhancementBuilder12.function(str48, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$26);
        ClassEnhancementBuilder classEnhancementBuilder13 = new ClassEnhancementBuilder(javaFunction4);
        C12999xe59eb435 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$27 = new C12999xe59eb435(signatureBuildingComponents4, str46, str36, str4, str16, str47, str45, str11, str12, str26);
        classEnhancementBuilder13.function(str48, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$27);
        SignatureBuildingComponents signatureBuildingComponents5 = signatureBuildingComponents3;
        ClassEnhancementBuilder classEnhancementBuilder14 = new ClassEnhancementBuilder(signatureBuildingComponents5.javaFunction("Supplier"));
        C13000xe59eb436 predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$28 = new C13000xe59eb436(signatureBuildingComponents5, str46, str36, str4, str16, str47, str45, str11, str12, str26);
        classEnhancementBuilder14.function(str34, predefinedEnhancementInfoKt$$special$$inlined$enhancement$lambda$28);
        PREDEFINED_FUNCTION_ENHANCEMENT_INFO_BY_SIGNATURE = signatureEnhancementBuilder5.build();
    }

    public static final Map<String, PredefinedFunctionEnhancementInfo> getPREDEFINED_FUNCTION_ENHANCEMENT_INFO_BY_SIGNATURE() {
        return PREDEFINED_FUNCTION_ENHANCEMENT_INFO_BY_SIGNATURE;
    }
}
